### ISSUE TITLE
Tracking issue: Implement FROST

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/redjubjub#21]
FROST is a threshold signature and DKG construction by @chelseakomlo and Ian Goldberg.

Link: https://crysp.uwaterloo.ca/software/frost/

In terms of the API, I think it would make sense to have the FROST implementation in a `frost` submodule separated from the main API, and feature-gate the entire submodule on a `frost` feature.

- [ ] Rebase #26 onto latest
- [ ] Use zkcrypto/jubjub's `SubgroupPoint` so as to be closer to 1:1 with the reference impl's Ristretto prime order group assumptions
- [ ] Triple-check the 'general' Schnorr sig divergence of `(z, c)` vs `(R, c)`

**Comment by burdges** [comment]
All published 2-round trip threshold/multi-signatres including FROST are vulnerable to the k-sum attack in https://eprint.iacr.org/2018/417 

You'll want to fix FROST to be three round trips.  I implemented the three round trip version with session types in https://github.com/w3f/schnorrkel/blob/master/src/musig.rs so maybe that's useful.

We found a "double deliniarization of nonces" trick that appears secure, but we're still struggling with a security proof.  I've already implemented the trick in https://github.com/w3f/schnorrkel/commit/fa6c35f832a4ae6f45e9c8e6858d90d1e2789fc7#diff-21a76c1f1f03ad91cc16d9ab499374dd but I'll caution that the "single deliniarization" with `REWINDS = 1` remains attackable.

Also, there is a new 2-round trip scheme from blockstream that derandomizes signing using bulletproofs, but only under submission, not actually released anywhere.  I've gotten mixed messages from them about whether it uses the secp256k1 mirror curve, but even if so then some SNARK likely works. 

Also, we've some recommended reading on the DKG side of this topic at https://github.com/w3f/bls/issues/6#issuecomment-573412444

**Comment by hdevalence** [comment]
As noted above, we have one of the FROST authors working on the implementation, so I think we'll manage :slightly_smiling_face:

 You can find more information on FROST and 2018/417 in this email, which addressed your concerns directly: https://mailarchive.ietf.org/arch/msg/cfrg/USYUleqIjS-mq93oGPSV-Tu0ndQ

**Comment by hdevalence** [comment]
In order to remain unopinionated, the messages generated while running the FROST protocols should be Serde'able, so that they can be serialized using whatever method is convenient for the library user.  This will require either adding Serde support to `jubjub` and `bls12_381` (allowing the use of derive for the messages) or implementing custom derives for the message types in `redjubjub`.

**Comment by hdevalence** [comment]
(It may be easier in the short term to use Serde's remote derive functionality, https://serde.rs/remote-derive.html , so that this doesn't block on upstream.)

**Comment by chelseakomlo** [comment]
Closing this as we merged #47 ; will open a separate issue for the DKG.
